### PR TITLE
http-server fixes + some tests

### LINKED ISSUE #7: `GET /exchanges` verify authz token
[relevant file](https://github.com/TBD54566975/tbdex-rest-api/blob/main/src/request-handlers/get-exchanges.ts)

### LINKED ISSUE #12: `POST /exchanges/:id/order` respond with 409 if order is not allowed given the current state of the exchange.
[relevant file](https://github.com/TBD54566975/tbdex-rest-api/blob/main/src/request-handlers/submit-order.ts)

### LINKED ISSUE #14: `POST /exchanges/:id/close` respond with 404 if exchange not found
[relevant file](https://github.com/TBD54566975/tbdex-rest-api/blob/main/src/request-handlers/submit-close.ts)

### LINKED ISSUE #15: `POST /exchanges/:id/close` respond with 409 if close is not allowed given the current state of the exchange
[relevant code](https://github.com/TBD54566975/tbdex-rest-api/blob/main/src/request-handlers/submit-close.ts#L29-L31)

### LINKED ISSUE #28: refactor validator to return all errors

### PR DESCRIPTION
**Pull request by phoebe-lew**
closes #15 
closes #14 
closes #12 
closes #7 
closes #28

### CODE REVIEW

File: packages/http-server/src/fakes.ts [hunk 1]
```diff
@@ -83,26 +83,46 @@ export const fakeOfferingsApi: OfferingsApi = {
...
+
   getOrderStatuses: function (): Promise<OrderStatus[]> {
     throw new Error('Function not implemented.')
   },
+
   getClose: function (): Promise<Close> {
     throw new Error('Function not implemented.')
+  },
+
+  addMessage: function (message: MessageKindClass): void {
```
Comment (phoebe-lew) [inline packages/http-server/src/fakes.ts:123]: @mistermoe I don't seem to have access to this method in the tests' `api.exchangesApi`. It is instantiated using `let api = new TbdexHttpServer()`. Any ideas on how to resolve?

File: packages/protocol/src/validator.ts
Comment (mistermoe) [inline packages/protocol/src/validator.ts:1]: thoughts on throwing a custom Error class that has an array of validation error objects? this way we can cleanly map validation errors to http-server response errors

File: packages/http-server/src/fakes.ts (hunk 1 above)
Comment (mistermoe) [reply packages/http-server/src/fakes.ts:123]: i think because the `ExchangesApi` interface doesn't have `addMessage`

File: packages/http-server/src/request-handlers/submit-order.ts [hunk 2]
```diff
@@ -27,14 +27,34 @@ export function submitOrder(opts: SubmitOrderOpts): RequestHandler {
...
+    const exchange = await exchangesApi.getExchange({id: message.exchangeId})
+    if(exchange == undefined) {
+      const errorResponse: ErrorDetail = { detail: `exchangeId: ${message.exchangeId} is undefined` }
 
-    const quote = await exchangesApi.getQuote({ exchangeId: message.exchangeId })
+      return res.status(404).json({ errors: [errorResponse] })
+    }
+
+    console.log('hiiiii')
+
```
Comment (frankhinek) [inline packages/http-server/src/request-handlers/submit-order.ts:38]: Noticed a logging statement.

Who doesn't love a polite web server.  Email servers always used to say HELO to each other 😄

File: packages/http-server/src/fakes.ts (hunk 1 above)
Comment (phoebe-lew) [reply packages/http-server/src/fakes.ts:123]: Hmm yeah, but we don't want `addMessage` to be on the interface, only in the test implementation.

File: packages/protocol/src/validator.ts
Comment (phoebe-lew) [reply packages/protocol/src/validator.ts:1]: Yeah could do

File: packages/http-server/src/request-handlers/submit-order.ts [hunk 3]
```diff
@@ -27,14 +27,34 @@ export function submitOrder(opts: SubmitOrderOpts): RequestHandler {
       return res.status(400).json({ errors: [errorResponse] })
     }
 
-    // TODO: return 409 if order is not allowed given the current state of the exchange. (#issue 4)
+    const exchange = await exchangesApi.getExchange({id: message.exchangeId})
+    if(exchange == undefined) {
+      const errorResponse: ErrorDetail = { detail: `exchangeId: ${message.exchangeId} is undefined` }
```
Comment (KendallWeihe) [inline packages/http-server/src/request-handlers/submit-order.ts:32]: Same thing here

File: packages/http-server/src/request-handlers/submit-order.ts (hunk 2 above)
Comment (KendallWeihe) [reply packages/http-server/src/request-handlers/submit-order.ts:38]: This is the way

File: packages/http-server/src/request-handlers/submit-order.ts [hunk 4]
```diff
@@ -27,14 +27,34 @@ export function submitOrder(opts: SubmitOrderOpts): RequestHandler {
...
+      return res.status(409).json({ errors: [errorResponse] })
+    }
+
+    const quote = exchange.find((message) => message.isQuote) as Quote
     if(quote == undefined) {
       const errorResponse: ErrorDetail = { detail: 'quote is undefined' }
       return res.status(404).json({errors: [errorResponse]})
     }
 
+    if(new Date(quote.expiresAt) < new Date(message.createdAt)){
```
Comment (KendallWeihe) [inline packages/http-server/src/request-handlers/submit-order.ts:52]: nit: I guess technically, the message creator could spoof the `createdAt` timestamp to get around this check

```suggestion
    if(new Date(quote.expiresAt) < new Date()){
```

File: packages/http-server/tests/submit-close.spec.ts [hunk 5]
```diff
@@ -48,9 +51,51 @@ describe('POST /exchanges/:exchangeId/close', () => {
...
+
+    const responseBody = await resp.json() as ErrorResponse
+    expect(responseBody.errors.length).to.equal(1)
+
+    const [ error ] = responseBody.errors
+    expect(error.detail).to.exist
+    expect(error.detail).to.include('is undefined')
+  })
+
+  xit(`returns a 409 if close is not allowed based on the exchange's current state`, async () => {
```
Comment (KendallWeihe) [inline packages/http-server/tests/submit-close.spec.ts:79]: Did you mean for this to be `xit`?

**Review by KendallWeihe — APPROVED** [review]
I know there are some open discussion points, but this lgtm ✅

File: packages/http-server/src/fakes.ts (hunk 1 above)
Comment (mistermoe) [reply packages/http-server/src/fakes.ts:123]: yep so in this case i think you'd just want to use `as FakeExchangesApi` where you're wanting to use the method

File: packages/protocol/src/validator.ts
Comment (mistermoe) [reply packages/protocol/src/validator.ts:1]: can also revert back to single error and punt multi error support to a separate PR if it feels like a large body of work!

File: packages/http-server/src/fakes.ts [hunk 6]
```diff
@@ -83,26 +83,51 @@ export const fakeOfferingsApi: OfferingsApi = {
...
+  exchangeMessagesMap: Map<string, MessageKindClass[]>,
+  addMessage(message: MessageKindClass): void
+  clearMessages(): void
+}
+
+export const fakeExchangesApi: FakeExchangesApi = {
+  exchangeMessagesMap: new Map<string, MessageKindClass[]>(),
+
   getExchanges: function (): Promise<MessageKindClass[][]> {
     throw new Error('Function not implemented.')
```
Comment (nitro-neal) [inline packages/http-server/src/fakes.ts:96]: can throw these instead - https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-not-implemented-error/

File: packages/http-server/src/request-handlers/submit-close.ts [hunk 7]
```diff
@@ -28,10 +28,19 @@ export function submitClose(opts: SubmitCloseOpts): RequestHandler {
       return res.status(400).json({ errors: [errorResponse] })
     }
 
-    // TODO: get most recent message added to exchange. use that to see if close is allowed (issue #1)
-    // return 409 if close is not allowed given the current state of the exchange.
+    const exchange = await exchangesApi.getExchange({id: message.exchangeId})
+    if(exchange == undefined) {
```
Comment (nitro-neal) [inline packages/http-server/src/request-handlers/submit-close.ts:32]: eventually can have a shared functions for these checks, or have a validator class that validates the exchange

**Review by nitro-neal — APPROVED** [review]
👍

File: packages/http-server/src/request-handlers/submit-close.ts (hunk 7 above)
Comment (phoebe-lew) [reply packages/http-server/src/request-handlers/submit-close.ts:32]: Yeah there is quite a bit of duplication across all the handlers!

File: packages/http-server/tests/submit-close.spec.ts [hunk 8]
```diff
@@ -1,17 +1,23 @@
...
 import type { Server } from 'http'
 
-import { TbdexHttpServer } from '../src/main.js'
+import { Close, DevTools, TbdexHttpServer } from '../src/main.js'
 import { expect } from 'chai'
+import { FakeExchangesApi } from '../src/fakes.js'
 
 let api = new TbdexHttpServer()
 let server: Server
+const did = await DevTools.createDid()
```
[the remark this answers is not in the document]
Comment (phoebe-lew) [reply packages/http-server/tests/submit-close.spec.ts:10]: Yep! it's using `import { DidIonMethod, DidKeyMethod } from '@web5/dids'`

File: packages/http-server/src/fakes.ts (hunk 6 above)
Comment (phoebe-lew) [reply packages/http-server/src/fakes.ts:96]: Is there a TS equivalent of this?
